#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'grooveshark'

Grooveshark.search ARGV[0] do |song|
  path = File.join File.dirname($0), "#{song.artist} - #{song.name}.mp3"
  puts "==> #{song.artist} - #{song.name} → #{path}"
  song.stream.dump File.open path, 'w'
end

puts "==> Done."
