#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'grooveshark'

tracks = GrooveShark.search ARGV[0] do |song|
  puts "==> #{song.artist} - #{song.name} (#{song.token})"
end
