#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'grooveshark'
require 'pp'

Grooveshark.search "ohoi" do |song|
  total, complete = song.stream.size, 0

  song.stream.each_chunk do |chunk|
    total = song.stream.size
    complete += chunk.size

    puts "%d%% complete" % [(complete * 100) / total]
  end
end
