#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'grooveshark'
require 'pp'

c = GrooveShark::Connection.new
p c.transmit 'getSearchResults', type: 'Songs', query: 'suspekt'}, true
